version: 2.1

jobs:
 
 java-build:
    
    docker:
      - image: cimg/openjdk:11.0
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD            
    
    steps:
     
      - checkout
      
      - restore_cache:
          keys: 
          - cache-key-{{ checksum "pom.xml" }}
          - cache-key-
      
      - run: mvn dependency:go-offline
      
      - save_cache:
          paths:
            - ~/.m2
          key: cache-key-{{ checksum "pom.xml" }}

      - run:
          name: Build
          command: mvn install

workflows:
       my_workflow_java: 
        jobs:
         - java-build

   
      
               
