version: 2.1

jobs:
 
 java-build:
    
    docker:
      - image: cimg/openjdk:11.0
      - image: circleci/node:10.16.3
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD            
    
    steps:
     
      - checkout
      
      - run: mvn dependency:go-offline
      
      - run:
          name: Build
          command: mvn install

workflows:
       my_workflow_java: 
        jobs:
         - java-build

   
      
               
